[package]
name = "raphtalia/firebase"
description = "Roblox Firebase API - https://github.com/raphtalia/FirebaseLuau"
version = "1.0.7"
license = "MIT"
registry = "https://github.com/UpliftGames/wally-index"
realm = "server"

[dependencies]
Promise = "evaera/promise@3.2.1"
